name: Check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Nix
        uses: nixbuild/nix-quick-install-action@v34

      - name: Check
        run: nix develop --command biome check ./app
