name: Perf

on: [push]

jobs:
  perf:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Start db and app
        run: docker compose -p tracing --profile services --profile app up -d --wait

      - name: Run k6
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/k6:/scripts \
            -e BASE_URL=http://app:3007 \
            --network tracing_shared \
            grafana/k6:latest run /scripts/script.js
